server:
  port: 8080
quartz:
  config:
    location: /spring-quartz.properties
spring:
  kafka:
    producer:
      # Kafka服务器
      bootstrap-servers: 192.168.21.128:9092,192.168.21.129:9092,192.168.21.130:9092
      # 发生错误后，消息重发的次数，开启事务必须设置大于0。
      retries: 3
      # acks=0 ： 生产者在成功写入消息之前不会等待任何来自服务器的响应。
      # acks=1 ： 只要集群的首领节点收到消息，生产者就会收到一个来自服务器成功响应。
      # acks=all ：(-1)只有当所有参与复制的节点全部收到消息时，生产者才会收到一个来自服务器的成功响应。
      # 开启事务时，必须设置为all
      acks: all
      # 当有多个消息需要被发送到同一个分区时，生产者会把它们放在同一个批次里。该参数指定了一个批次可以使用的内存大小，按照字节数计算。
      batch-size: 16384
      # 生产者内存缓冲区的大小。
      buffer-memory: 33554432
      #如果数据迟迟未达到batch.size，sender等待linger.time之后就会发送数据。单位ms，默认值是0ms，表示没有延迟。生产环境建议该值大小为50-100ms之间。
      linger-ms: 50
      # 键的序列化方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 值的序列化方式
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    #      interceptor-classes: com.ctid.interceptor.KafkaProducerInterceptor
    consumer:
      # Kafka服务器
      bootstrap-servers: 192.168.21.128:9092,192.168.21.129:9092,192.168.21.130:9092
      group-id: dataCenter
      # 自动提交的时间间隔 在spring boot 2.X 版本中这里采用的是值的类型为Duration 需要符合特定的格式，如1S,1M,2H,5D
      #auto-commit-interval: 2s
      # 该属性指定了消费者在读取一个没有偏移量的分区或者偏移量无效的情况下该作何处理：
      # earliest：当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，从头开始消费分区的记录
      # latest：当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，消费新产生的该分区下的数据（在消费者启动之后生成的记录）
      # none：当各分区都存在已提交的offset时，从提交的offset开始消费；只要有一个分区不存在已提交的offset，则抛出异常
      auto-offset-reset: earliest
      # 是否自动提交偏移量，默认值是true，为了避免出现重复数据和数据丢失，可以把它设置为false，然后手动提交偏移量
      enable-auto-commit: false
      #消费者偏移量向Kafka提交的频率，默认5s。
      auto-commit-interval-ms: 10000
      # 键的反序列化方式-错误处理
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      # 值的反序列化方式
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: '*'
        #序列化、反序列化一致
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      # 这个参数定义了poll方法最多可以拉取多少条消息，默认值为500。如果在拉取消息的时候新消息不足500条，那有多少返回多少；如果超过500条，每次只返回500。
      # 这个默认值在有些场景下太大，有些场景很难保证能够在5min内处理完500条消息，
      # 这个参数对批量消费和逐条消费都有效
      max-poll-records: 100
    properties:
      # 消费者处理消息的最大时长，默认是5分钟。超过该值，该消费者被移除，消费者组执行再平衡。
      max.poll.interval.ms: 600000 #10分钟
    #      intercepts.classes: com.ctid.interceptor.KafkaProducerInterceptor

    listener:
      # 在侦听器容器中运行的线程数,当concurrency > partition count 将有线程被浪费
      concurrency: 2
      # 自动提交关闭，需要设置手动消息确认
      # 手动ack：manual手动ack时 如果有异常会尝试一直消费
      # 手动ack：消费有异常时停止
      ack-mode: manual_immediate
      # 消费监听接口监听的主题不存在时，默认会报错，所以设置为false忽略错误
      missing-topics-fatal: false
      # 消费者在拉取消息时，如果没有消息，会等待多久，默认是500ms
      poll-timeout: 15000
      # 消费模式：single=单条消息，batch=批量消费
      type: single
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver