server:
  port: 8080
quartz:
  config:
    location: /spring-quartz.properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  quartz:
    scheduler-name: FraudQuartzScheduler
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: FraudQuartzScheduler
            instanceId: AUTO
            skipUpdateCheck: true

          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 20
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            useProperties: false
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 20000
            misfireThreshold: 60000
            dataSource: quartzDataSource
            acquireTriggersWithinLock: true

          dataSource:
            quartzDataSource:
              driver: com.mysql.cj.jdbc.Driver
              URL: jdbc:mysql://localhost:3306/quartz?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
              user: root
              password: password
              maxConnections: 10
              connectionProvider:
                class: com.ctid.config.DruidConnectionProvider
              validationQuery: SELECT 1
              idleConnectionValidationSeconds: 50